# SpectatorPlus ~by pgmann

# YOU DON'T NEED TO CHANGE ANYTHING HERE!
# Please don't change the settings below.

# NOTE: If you change the world name, you will need to set the
# lobby again. You can do this ingame using '/spectate setlobby'.

# TECHNICAL STUFF

# Spectator lobby position
active: false
xPos: 0
yPos: 0
zPos: 0
world: null

# Spectator arena positions: next arena
nextarena: 1
mode: any
